### PR TITLE
Add option for select publish date format in article

### PR DESCRIPTION
**Pull request by JuraSN**
screen

### CODE REVIEW

**Comment by ppoffice** [comment]
@JuraSN Is it better to make it an option to turn the relative date to a full date instead of adding a new line below?

**Comment by JuraSN** [comment]
I wanted both the full date and the relative date to be visible.

Maybe add three options to choose from?

1. Exact date
2. Relative date
3. Both together as <Exact date (relative date)>

**Comment by ppoffice** [comment]
I just feel like the metadata should be in the same line, no matter it's full date or not.

**Comment by JuraSN** [comment]
Fixed the code for displaying the date in one line.

Option "**relative**" and if option is absend in config:
relative


Option "**full**":
full


Option "**relative_full**":
relative_full


Option "**full_relative**":
full_relative

**Pull request merged**
